config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
  get 'page', to: 'pages#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
  end

  def show
    @id = 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Casamento Bruna e Lucas!</title>
    <link rel = "icon" href = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRJmvroCVtA5-0lSzW7uAWP8sraT9RU85G5u0yyou8XB-jhE04zzl5tzdrT0tXjuJQym0&usqp=CAU"
        type = "image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="m-5">
    <%= render 'shared/navbar' %>
    </div>
    <div class="p-4">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
     <section id="home" class="d-flex">
      <div class="container align-self-center">
        <div class="row">
          <div class="col-md-12 capa">

            <div>
             <%= image_tag "sim.jpg", style: 'height:70%;width:70%'%>

              </div>

          <div class="col-md-12 capa"></div>
            <div id="carousel-spotify" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">

                <div class="carousel-item active">
                  <h1>Casamento Bruna e Lucas</h1>
                  <%= link_to "CONFIRME SUA PRESENÇA", "https://forms.gle/2LC7XGy3x1129AH87", class: "btn btn-lg btn-custom btn-roxo",
                   data: { confirm: "Voce esta sendo direcionado ao formulario de convidados. É isso que deseja?" }%>

                  <%= link_to 'Presenteie o casal!', page_path(1), class: "btn btn-lg btn-custom btn-roxo"%>
                  </div>
                <div class="carousel-item">
                  <h1>Informações Gerais</h1>
                    <%= link_to "Data & Local", pages_path, class: "btn btn-lg btn-custom btn-roxo btn-tela-pequena"%>
                  </a>
                </div>

              </div>


              <a href="#carousel-spotify" class="carousel-control-prev" data-slide="prev">
                <i class="fas fa-angle-left fa-3x"></i>
              </a>

              <a href="#carousel-spotify" class="carousel-control-next" data-slide="next">
                <i class="fas fa-angle-right fa-3x"></i>
              </a>

            </div>

          </div>
        </div>
      </div>
    </section>

    <div id="days_countdow">
      <h2 id="days_title">Faltam apenas <strong><%= (Date.new(2022,11,26) - Date.today).to_i%> </strong> Dias!</h2>
    </div>

    <%= render 'shared/history' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/pages/index.html.erb
<div class= "container my-3">
  <section id="evento" class="caixa">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="row albuns">
                <div class="col-md-6 sumir-celular">
                <%= image_tag "img1.jpg", style: 'height:100%;width:100%' %>
                </div>
                <div class="col-md-6 sumir-celular">
                  <%= image_tag "img2.jpg", style: 'height:100%;width:100%' %>
                </div>
              </div>
              <div class="row albuns">
                <div class="col-md-6">
                  <%= image_tag "img3.jpg", style: 'height:100%;width:100%' %>
                </div>
                <div class="col-md-6 sumir-celular">
                  <%= image_tag "img4.jpg", style: 'height:100%;width:100%' %>
                </div>
              </div>
            </div>
            <div class="col-md-6">

              <h2>Como será o evento?</h2>
              <p>Nossa cerimônia e festa ocorrerão dia 26/11 no mesmo local, no Espaço La Playa, que fica no Hotel Atlântico Sul. A cerimônia será na cobertura e começará às 16h30 para aproveitarmos a vista da praia e da Pedra do Pontal. Em seguida, vamos todos para o salão para começar a festa! Esperamos todos lá. </p>
              <br>
              <h3>Cerimônia - > 16h às 17h</h3>
              <br>
              <h3>Festa - > 17h às 22h</h3>

            </div>
          </div>
        </div>
      </section>



          <section id="facil" class="caixa">
        <div class="container">
          <div class="row">
            <div class="col-md-4">

              <h2>Fácil</h2>
              <h3>Local</h3>
              <p>Hotel Atlântico Sul. Endereço: Av. Lúcio Costa, n. 18.000, Recreio dos Bandeirantes, Rio de Janeiro. Tel: (21) 3418-9100.
              </p>

              <h3>Estacionamento</h3>
              <p>O hotel comporta estacionamento privado com serviço de valet gratuito para todos os convidados do casamento.
              </p>

              <h3>Entrada</h3>
              <p>Chegando ao local, basta se dirigir à recepção e indicar seu nome para receber as orientações.
              </p>

            </div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-6">
                  <%= image_tag "hotel.jpg", style: 'height:100%;width:100%' %>
                </div>
                <div class="col-md-6 sumir-celular">
                  <%= image_tag "cerimonia.jpg", style: 'height:100%;width:100%' %>
                </div>
              </div>
              <div class="row albuns">
                <div class="col-md-6 sumir-celular">
                <%= image_tag "valet.jpg", style: 'height:100%;width:100%' %>
                </div>
                <div class="col-md-6">
                <%= image_tag "moca.jpg", style: 'height:100%;width:100%' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</div>

app/views/pages/show.html.erb
<div class="gift_container">

  <div class="gift_main_text">

    <h2>Olá e bem vindo a lista de presentes!</h2>
    <p>
      Como já temos nossa casinha montada, resolvemos pedir de presente de casamento as atividades da Lua de Mel.
      Decidimos ir para Bahia e vamos ficar 1 semana no La Torre Resort All Inclusive em Porto Seguro para descansar bastante dessa vida de doutorandos e pegar um solzinho.
      A viagem vai ser no final de junho de 2023. Longe, né? Mas é quando poderemos tirar férias juntos.
      Colocamos abaixo o custo total das passagens, hospedagem e passeios junto de um qr-code para que possam contribuir com o valor que desejarem dar de presente.
    </p>

  </div>


  <div class="gifts">

    <div class="gift_title">
      <h3>PASSAGEM </h3>
    </div>

    <div class="gift_item">
      <div class="gift_banner">
      <%= image_tag "airplane.jpg", style: 'height:100%;width:100%;object-fit:contain'%>
      </div>

      <div class="gift_item_desciption">
        <div class="gift_text">
        <p> Precisamos chegar até a Bahia, não é mesmo? Aqui está incluído o trajeto de ida e volta do Rio para Porto Seguro em jun/2023. </p>
        </div>

        <div class="gift_value">
        <h6>Pagamos:  R$ 2.000,00</h6>
        </div>
      </div>
    </div>

      <div class="gift_title">
      <h3>HOSPEDAGEM</h3>
    </div>

    <div class="gift_item">
      <div class="gift_banner">
      <%= image_tag "beach_club.jpg", style: 'height:100%;width:100%;object-fit:contain'%>
      </div>

      <div class="gift_item_desciption">
        <div class="gift_text">
        <p> Para relaxar de verdade, escolhemos um Resort All Inclusive na praia do Mutá. Lá teremos: comida, bebida, spa, piscina, vista para praia e muito mais. </p>
        </div>

        <div class="gift_value">
        <h6>Pagamos: R$ 8.000</h6>
        </div>
      </div>
    </div>

    <div class="gift_title">
      <h3>PASSEIOS</h3>
    </div>

    <div class="gift_item">
      <div class="gift_banner">
      <%= image_tag "the_corner.jpg", style: 'height:100%;width:100%;object-fit:contain'%>
      </div>

      <div class="gift_item_desciption">
        <div class="gift_text">
        <p> Além da praia, Porto Seguro tem muitos passeios interessantes que vamos fazer, como conhecer o centro histórico, a costa do descobrimento e o parque marinho do recife de fora. </p>
        </div>

        <div class="gift_value">
        <h6>Pagamos: R$ 1.000,00</h6>
        </div>
      </div>
    </div>
    </div>




    <div class="gift_title">
      <h3>Abaixo seguem as informações bancárias</h3>
    </div>

    <div class="gift_payment">

      <div class="gift_pix">
          <%= image_tag "pix_kc.jpg", style: 'height:100%;width:100%'%>
      </div>

      <div class="gift_bank">
        <h5 class="m-5">Copie o texto (código PIX)</h5>
        <p>00020126980014BR.GOV.BCB.PIX0124brunaccandrade@gmail.com0248Presente de casamento Bruna e Lucas (Lua de Mel)5204000053039865802BR5917BRUNA C C ANDRADE6009SAO PAULO6226052234EDn7DojGriLYURsxDkdA6304FCA2</p>
      </div>

    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
 <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12 d-flex justify-content-center">
            <p>&copy 2022 Lucas Krause &
                <%= link_to "Raphael Resende", "https://www.linkedin.com/in/raphael-resende-breitschaft-426685163/", target: '_blank', class: 'link-footer', margin: '5px' %>
                . Todos os direitos reservados.
            <%= link_to "Código aqui:", "https://github.com/raphael-rbbr/wedding_Bruna-Lucas", target: '_blank', class: 'link-footer' %>
            </p>
          </div>
        </div>
      </div>
    </footer>

app/views/shared/_history.html.erb
<div class= "container m-2 p-3">
    <h3>Nossa História:</h3>
    <p>Se você está nesse site, certamente sabe que a história é longa demais para contar aqui e com certeza participou de boa parte dela. Juntos desde os 18 anos, nenhum dos dois tinha a menor expectativa que uma festa conjunta do Santo Agostinho e do Santo Inácio e alguns amigos em comum nos trariam até aqui quase exatos 10 anos depois. Já são mais de 3650 dias que incluem:  faculdade (e mestrado… e doutorado…), 1 intercâmbio, 2 casas, 1 eurotrip, 1 filhote de patas, 1 pandemia e incontáveis histórias incríveis. Ainda assim, a sensação é que essa a história está só começando. E é um prazer dividir tudo com vocês.</p>
</div>

app/views/shared/_navbar.html.erb
      <nav class="navbar navbar-expand-md navbar-light fixed-top navbar-transparente">
        <div class="container icone-barra">


          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <i class="fas fa-bars text-white"></i>
          </button>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
             <li class="nav-item">
                 <%= link_to "B + L", root_path, class: "navbar-brand"%>
              </li>
              <li class="nav-item divisor sumir-celular"></li>

              <li class="nav-item quebra-celular">
               <%= link_to "Data & Local", pages_path, class: "navbar-brand"%>
              </li>

              <li class="nav-item divisor sumir-celular"></li>

              <li class="nav-item">
                <%= link_to "Confirmar Presença", "https://forms.gle/2LC7XGy3x1129AH87",target: '_blank', class: "navbar-brand",
                data: { confirm: "Voce esta sendo direcionado ao formulario de confirmação de presença. É isso que deseja?" }%>
              </li>

              <li class="nav-item divisor sumir-celular"></li>

              <li class="nav-item">
                <%= link_to "Lista de presentes", page_path(1), class: "navbar-brand"%>
              </li>
            </ul>
          </div>

        </div>
      </nav>